name: Build Nightly Grid Editor

on: 
  push:
    branches:
      - stable
      - dev

jobs:
  job_1:
    name: Build Nightly Grid Editor
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ''
          submodules: true

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16.6'        

      - name: Install dependencies
        run: npm i
        env:
          UA: ${{ secrets.UA }}
      
      - name: Build        
        run: npm run export:nightly
        if: ${{ always() }}
        env:     
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # macOS Code signing certificates
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

          # windows Code signing
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

          # macOS notarization API key
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: dist/*.*
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2

  job_2:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.6'        

      - run: npm i
      
      - name: 'Test'
        run: npm test
